import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Layout.module.scss";
import "bootstrap/dist/css/bootstrap.css";
import { IoLocationOutline } from "react-icons/io5";
import { HiOutlineMail, HiOutlineClock } from "react-icons/hi";
import {
  BsInstagram,
  BsTwitter,
  BsPinterest,
  BsFacebook,
} from "react-icons/bs";
import { COLORS } from "@/enums/ColorEnum";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <nav className="py-2 bg-light border-bottom" id={styles["header-top"]}>
        <div className="container d-flex flex-wrap">
          <IoLocationOutline color={COLORS.GREEN} />
          <HiOutlineMail color={COLORS.GREEN} />
          <HiOutlineClock color={COLORS.GREEN} />
          <BsTwitter color={COLORS.GREEN} />
          <BsFacebook color={COLORS.GREEN} />
          <BsInstagram color={COLORS.GREEN} />
          <BsPinterest color={COLORS.GREEN} />
        </div>
      </nav>
      <header className="py-3 mb-4 border-bottom">
        <div className="container d-flex flex-wrap justify-content-center">
          <a
            href="/"
            className="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none"
          >
            <svg className="bi me-2" width="40" height="32">
              <use href="#bootstrap" />
            </svg>
            <span className="fs-4">Double header</span>
          </a>
          <form className="col-12 col-lg-auto mb-3 mb-lg-0" role="search">
            <input
              type="search"
              className="form-control"
              placeholder="Search..."
              aria-label="Search"
            />
          </form>
        </div>
      </header>
      <div className="container">
        <div className="row">{children}</div>
      </div>
    </>
  );
}
